### ISSUE TITLE
Oh god why MCPE 1.5 - fixes for the death of MoveEntityPacket

### ISSUE THREAD

**Issue by JUSTaMod** [jojoe77777/SlapperRotation#13]
Since I still don't get GitHub pull requests - have a phar.

*phar removed*

Btw. Yes. I do feel like a d**k for posting this here. But it's for the _people_ man. The _people_.

For [this commit.](https://github.com/pmmp/PocketMine-MP/commit/df3870a1122ff9fbeb880fa7fa3144edf6a2e7ea)

**Comment by YHC2538** [comment]
I was just about to post that issue, you helped me man!
