### ISSUE TITLE
why dont you add SlapperRotation and SlapperChache to the main Slapper plugin? 

### ISSUE THREAD

**Issue by RocoWayne** [jojoe77777/SlapperRotation#3]
Maybe the admin can set true/false of this options in a config file instead of installing 3 plugins for slapper. Is only a suggestion.

**Comment by jojoe77777** [comment]
Add-ons are add-ons (not referring to MCPE addons). They shouldn't be integrated into the core.

There's very few people who actually try to use SlapperCache for example, and even less people who understand how to use it properly.
