### ISSUE TITLE
Can you help me ... ?

### ISSUE THREAD

**Issue by MilkAndCookiz** [jojoe77777/SlapperRotation#7]
![noxmwse9](https://user-images.githubusercontent.com/24322800/27015737-75ce4f46-4f16-11e7-9af1-29a13debeb5a.jpg)
it's my Console spam, can you fix it? I use the last version of Cookie-MP and it makes me this bug. I hope this does not come from my software....

**Comment by jojoe77777** [comment]
> Cookie-MP

**Comment by PainTR** [comment]
im using PM-MP and i have the same error on console
