### ISSUE TITLE
PlayerMoveEvent Error.

### ISSUE THREAD

**Issue by Enrick3344** [jojoe77777/SlapperRotation#9]
When players join they get this error from SlapperRotation on ALPHA9. Im using PMMP.

`` [Server thread/CRITICAL]: Could not pass event 'pocketmine\event\player\PlayerMoveEvent' to 'SlapperRotation v1.1': Argument 1 passed to pocketmine\utils\BinaryStream::putLFloat() must be of the type float, null given, called in phar:///root/PocketMine-MP.phar/src/pocketmine/network/mcpe/protocol/MovePlayerPacket.php on line 81 on SlapperRotation\Main``

**Comment by XDqrkneZ** [comment]
bump
